apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: thanos-query
  namespace: default
  labels:
    app: thanos-query
spec:
  endpoints:
  - honorLabels: true
    port: http
  selector:
    matchLabels:
      app: thanos-query
