apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: kubernetes-controller
    app.kubernetes.io/instance: katacode-default
    app.kubernetes.io/name: thanos-receive-controller
    app.kubernetes.io/part-of: katacode
    app.kubernetes.io/version: master-2020-02-06-b66e0c8
  name: thanos-receive-controller
  namespace: default
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/component: kubernetes-controller
    app.kubernetes.io/instance: katacode-default
    app.kubernetes.io/name: thanos-receive-controller
    app.kubernetes.io/part-of: katacode
