apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: kubernetes-controller
    app.kubernetes.io/instance: katacoda-default
    app.kubernetes.io/name: thanos-receive-controller
    app.kubernetes.io/part-of: katacoda
    app.kubernetes.io/version: master-2020-02-06-b66e0c8
  name: thanos-receive-controller
  namespace: default
spec:
  endpoints:
  - honorLabels: true
    port: http
  selector:
    matchLabels:
      app.kubernetes.io/component: kubernetes-controller
      app.kubernetes.io/instance: katacoda-default
      app.kubernetes.io/name: thanos-receive-controller
      app.kubernetes.io/part-of: katacoda
