apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: database-write-hashring
    app.kubernetes.io/instance: katacoda-default
    app.kubernetes.io/name: thanos-receive
    app.kubernetes.io/part-of: katacoda
    app.kubernetes.io/version: master-2020-05-24-079ad427
    app: prometheus
  name: thanos-receive-default
  namespace: default
spec:
  endpoints:
  - honorLabels: true
    port: http
  selector:
    matchLabels:
      app.kubernetes.io/component: database-write-hashring
      app.kubernetes.io/instance: katacoda-default
      app.kubernetes.io/name: thanos-receive
      app.kubernetes.io/part-of: katacoda
