apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: thanos-query
  namespace: default
  labels:
    app: thanos-query
spec:
  selector:
    matchLabels:
      app: thanos-query
  endpoints:
  - port: http
    interval: 15s

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: thanos-ruler
  namespace: default
  labels:
    app: thanos-ruler
spec:
  selector:
    matchLabels:
      app: thanos-ruler
  endpoints:
    - port: http
      interval: 15s

