apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus
    prometheus: demo
  name: prometheus-demo
  namespace: default
spec:
  ports:
  - name: web
    port: 9090
    protocol: TCP
    targetPort: web
  - name: thanos-http
    port: 19090
    protocol: TCP
    targetPort: thnaos-http
  selector:
    prometheus: demo
