apiVersion: v1
kind: Service
metadata:
  name: thanos-ruler
  namespace: default
  labels:
    app: thanos-ruler
spec:
  selector:
    app: thanos-ruler
  ports:
  - name: http
    port: 9094
    targetPort: http
