apiVersion: v1
kind: Service
metadata:
  name: thanos-storeapi
  namespace: default
  labels:
    app: thanos-storeapi
spec:
  selector:
    storeapi: true
  ports:
  - name: grpc
    port: 10901
    targetPort: grpc
